[package]
name = "embedder-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
reqwest = { version = "0.12.12", features = ["json"] }

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "1.42.0", features = ["full"] }
