[package]
name = "embedder"
version = "0.1.0"
edition = "2021"

[dependencies]
embedder-core = { workspace = true }

[workspace.dependencies]
embedder-core = { path = "embedder-core", version = "0.1.0" }
