services:
  app:
    image: ghcr.io/excoffierleonard/embedder
    container_name: embedder-app
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      OLLAMA_API_URL: ${OLLAMA_API_URL:-http://ollama:11434/api/embed}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "${EMBEDDER_APP_PORT:-8080}:8080"

  ollama:
    image: ollama/ollama
    container_name: embedder-ollama
    restart: unless-stopped
