services:
  app:
    image: ghcr.io/excoffierleonard/embedder
    container_name: embedder-app
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${EMBEDDER_APP_PORT:-8080}:8080"
    networks:
      - embedder

networks:
  embedder:
    name: embedder