services:
  app:
    image: ghcr.io/excoffierleonard/embedder
    container_name: embedder-app
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${EMBEDDER_APP_PORT:-8080}:8080"
    networks:
      - embedder

  db:
    image: ankane/pgvector # Need to implement more secure option later
    container_name: embedder-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432 # For external access
    networks:
      - embedder

networks:
  embedder:
    name: embedder