[package]
name = "embedder-web"
version = "0.1.0"
edition = "2021"

[dependencies]
embedder-core = { path = "embedder-core", version = "0.1.0" }
actix-web = { workspace = true }
serde = { workspace = true }
